apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mcp-oauth-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.application.k8s.secretName | quote }}]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mcp-oauth-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mcp-oauth-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mcp-oauth-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
